<?php
#!/usr/local/bin/php
?><table width=100% cellpadding=0 cellspacing=1 border=0>
<tr><th>Attack</th></tr><tr><td>Be careful when approaching or attacking monster they have memory and will remember you, and tend to take revenge if you do not kill them off.<br>
<?php
$attack='';
$difficulty=1;
if(!empty($_GET['attack'])){$attack=clean_post($_GET['attack']);}
if(!empty($_POST['attack'])){$attack=clean_post($_POST['attack']);}
if(!empty($_POST['action'])){$action=clean_post($_POST['action']);}else{$action='';}
if(!empty($_POST['difficulty'])){$difficulty=round(clean_post($_POST['difficulty']));}

//KINGDOMS
if($dresults = mysqli_query ($link, "SELECT * FROM `$tbl_kingdoms` WHERE `x`='$row->x' and `y`='$row->y' ORDER BY `id` DESC LIMIT 1")) {
if(mysqli_num_rows($dresults) >= 1){
if ($krow = mysqli_fetch_object ($dresults)) {
	mysqli_free_result ($dresults);
}
}
}
//KINGDOMS


//PLAYER STATS
if(empty($total_stats)){$total_stats=total_stats();}
if(empty($total_charmed)){$total_charmed=total_charms();}
$i=0;
foreach ($stats as $val) {
if($i >= 3){
	$row->$val = ($row->$val/100)*(100+$total_charmed[$i]);
}
}
$battle_stats=battle_stats();
//PLAYER STATS

if ($attack == 'engage'){
$engage = '';
}else{
$engage = " and `id`='$attack'";
}

//SUPER WAR ATTACK ALL $to_attack_all VALUE GENERATED BY MONSTER LIST ABOVE
/*
if(!empty($to_attack_all) and $row->freeplay >= 5){
$engage = " AND `id` IN($attack)";
print '<h1>KILLEMALL!</h1>';
}
*/
//SUPER WAR ATTACK ALL $to_attack_all VALUE GENERATED BY MONSTER LIST ABOVE



if($maresult = mysqli_query ($link, "SELECT * FROM `$tbl_fight` WHERE `x`='$row->x' AND `y`='$row->y'".$engage." ORDER BY `id` DESC LIMIT $max_monsters")) {
	//print mysqli_num_rows($maresult);
if(mysqli_num_rows($maresult) >= 1){

if($row->life >= 1) {
											// MONSTER LEVEL EXTRACTED FROM THE $array_monsters $mrow->charname

while ($mrow = mysqli_fetch_object ($maresult)) {
	//print 'aaaaaaaaaaaaaaaa';
//FIGHT ON
$mon_stats = monster_stats($mrow);
//$mon_exp =(96+((1+$mrow->charname)*(1+$mrow->charname))*$mrow->charname)*(1+$mrow->dupe); //lol1 exp
$mon_exp = (($mrow->charname*$mrow->charname)+$mrow->mana+$mrow->stamina)*(1+$mrow->dupe);
$mon_exp -= $row->level;
if ($mon_exp <= 1) {$mon_exp = 10;}
if($mon_exp > $max_exp_gain){$mon_exp = $max_exp_gain+$mrow->charname+$mrow->dupe;}


$fight_on .= 'Approaching <b>'.$array_monsters[$mrow->charname].'</b>, an <b>'.$array_strength[$mrow->dupe].'</b> level <b>'.$mrow->charname.'</b> monster with <b>'.number_format($mrow->life).'</b> life.<br>';

//TEST
/*
print '<hr color=red>';
foreach ($mrow as $key=>$val){print $key.':'.$val.' ';}
print '<hr color=red>';
foreach ($mon_stats as $val){print $val.' ';}
print '<hr color=red>';
print_r($_GET);print_r($_POST);
print '<hr color=red>';
print '<pre>';
print_r($mon_stats);
print_r($mrow);
print_r($battle_stats);
print '</pre>';
*/
//TEST

//ENGAGE BATTLEFIELD



if (!empty($action)) {
	$to_update_monster ="`timer`='$current_time', `ocharname`='$row->charname'";
$fight_on .= 'Estimated power of the monster <b>'.number_format(array_sum($mon_stats)/14).'</b>, your total power is <b>'.number_format(array_sum($battle_stats)/14).'</b>.<br>'; // and '.number_format($mon_exp).' experience.<br>';

//KINGDOMS FORCES
if(!empty($is_kingdom["$row->x-$row->y"])){
if(!empty($krow->elites)){
	if ($krow->elites >= 1){
	$elites_damage = round(rand($krow->elites+100,($krow->elites*1000))+$row->level);
	$fight_on .= 'Kingdom is sending <b>'.number_format($krow->elites).'</b> elites, doing <b>'.number_format($elites_damage).'</b> damage.';
	$to_update_monster .= ", `life`=`life`-$elites_damage";
	$mrow->life -= $elites_damage;
	}
}
//KINGDOMS FORCES
//KINGDOM PLAYER FORCES

if($kpsult = mysqli_query ($link, "SELECT `level`,`charname` FROM $tbl_members WHERE `x`='$row->x' AND `y`='$row->y' and `kid`='$row->kid' and `id`!='$row->id' ORDER BY `id` DESC LIMIT 10")){
if(mysqli_num_rows($kpsult) >= 1) {
	$kp_damage = 1;
while($kpow = mysqli_fetch_object ($kpsult)){
	$kp_damage += rand($kpow->level,($kpow->level*10));
	//print $kpow->charname;
}
mysqli_free_result ($kpsult);

	$fight_on .= 'Your kingdom mates are doing <b>'.number_format($kp_damage).'</b> damage.';
	$to_update_monster .= ", `life`=`life`-$kp_damage";
	$mrow->life -= $kp_damage;
}
}
}
//KINGDOM PLAYER FORCES
$to_damage = 0;
$to_steal_life = 0;
$to_steal_mana = 0;
$to_steal_stamina = 0;
$col_me='';

if ($action == 'use weapon') {
	attack_use_weapon();
	$col_me = $col_melee;
	$to_update .= ", `stamina`='$row->stamina'";
} elseif ($action == 'cast spell') {
	attack_cast_spell();
	$col_me = $col_magic;
	$to_update .= ", `mana`='$row->mana'";
} elseif ($action == 'heal spell') {
	attack_cast_healing();
} elseif ($action == 'use battle skill') {
	$i=0;
	while ($i < $max_rounds and $i<1+$row->battleskill and $mrow->life > 0 and $row->life > 0){
	//for ($i=0;$i<=1+$row->battleskill;$i++){if($i >= $max_rounds){break;}
	attack_use_weapon();
	$i++;
}
	$col_me = $col_melee;
	$fight_on .= 'Strikes '.$i.' times.';
	$to_update .= ", `stamina`='$row->stamina'";
} elseif ($action == 'cast magic skill') {
	$i=0;
	while ($i < $max_rounds and $i<1+$row->magicskill and $mrow->life > 0 and $row->life > 0){
	//for ($i=0;$i<=1+$row->magicskill;$i++){if($i >= $max_rounds){break;}
	attack_cast_spell();
	$i++;
}
	$col_me = $col_magic;
	$fight_on .= 'Casted '.$i.' times.';
	$to_update .= ", `mana`='$row->mana'";
} elseif ($action == 'run or hide') {
	if($row->quest <= 18) {
	$to_update .= ", `honor`=`honor`-0.01";
	}
if(rand(1,100) <= $min_succes_chance+$row->honor) {
	$fight_on .= 'Succes! You duck away quickly behind the bushes and <b>'.$array_monsters[$mrow->charname].'</b> was still looking in the wrong bushes!<br>';
	mysqli_query ($link, "UPDATE `$tbl_fight` SET `ocharname`='' WHERE `id`='$mrow->id' LIMIT 1") or die_nice(mysqli_error().'monsters run away');
}else{
	if (rand(1,10) <= 5){
	$fight_on .= 'Failed! You run as hard as you can but <b>'.$array_monsters[$mrow->charname].'</b> is keeping up with you.<br>';
	}else{
	$fight_on .= 'Failed! You duck away quickly behind the bushes and <b>'.$array_monsters[$mrow->charname].'</b> has found you!<br>';
	}
}
}

if($to_damage>1){

	$fight_on .= '<font color="'.$col_me.'">You '.$action.' for '.number_format($to_damage).' damage.</font>';
	mysqli_query ($link, "INSERT INTO `$tbl_paper` values ('','6','$mrow->id','$current_date','$row->sex $row->charname ".$action." ".number_format($to_damage)." damage.','$current_time')") or die_nice(mysqli_error().'deploy paper');

	//STEAL
	$to_steal = '';
	if($to_steal_life>=1){$to_update .= ", `life`=`life`+$to_steal_life";$to_steal .= 'Stealing '.number_format($to_steal_life).' life.';}
	if($to_steal_mana>=1){$to_update .= ", `mana`=`mana`+$to_steal_mana";$to_steal .= 'Stealing '.number_format($to_steal_mana).' mana.';}
	if($to_steal_stamina>=1){$to_update .= ", `stamina`=`stamina`+$to_steal_stamina";$to_steal .= 'Stealing '.number_format($to_steal_stamina).' stamina.';}
	if(!empty($to_steal)){$fight_on .= '<font color="'.$col_steal.'">'.$to_steal.'</font><br>';}
	//STEAL
}

monster_does();

	//WIN OR lOSS
if (!empty($action)) {
if ($mrow->life < 0 and $row->life > 0) {
	$fight_on .= 'You have slain <b>'.$array_monsters[$mrow->charname].'</b>, you gain <b>'.number_format($mon_exp).'</b> experience!<br>';
		if ($freeplay >= 1){
		$mon_exp *= 2;
		}
		$to_update .= ", `exp`=`exp`+$mon_exp";
if($mrow->charname*$mrow->dupe >= $row->level) {
	//print 'aaaaaaaaaaaaaaaaaaaaaa';
	$to_update .= ", `honor`=`honor`+0.01";
}
monster_dies_or_revives($mrow->id);
	$drop_gold = drop_something($mrow->charname);


	//$drop_gold = 10000;
	//DROP GOLD AND TAX COLLECTIONS
if($drop_gold >= 1){
	$fight_on .= '<font color="'.$col_drop.'">Found <b>'.number_format($drop_gold).'</b> gold';
if(!empty($krow->tax) and !empty($krow->charname)){
if ($krow->tax >= 1 and $krow->tax <= 75){
	$drop_gold /= 100;
	$tax_gold = round($drop_gold*$krow->tax);
	$drop_gold = round($drop_gold*(100-$krow->tax));
	$fight_on .= ' kingdom tax <b>'.number_format($tax_gold).'</b> gold';
mysqli_query ($link, "UPDATE `$tbl_kingdoms` SET `gold`=`gold`+'$tax_gold' WHERE `id`='$krow->id' LIMIT 1") or die_nice(mysqli_error().'tax collection');
mysqli_query ($link, "INSERT INTO `$tbl_paper` values ('','5','$krow->charname','$current_date','Tax collected by <b>$krow->kingdom</b> kingdom from $row->sex $row->charname <b>".number_format($tax_gold)."</b> gold.','$current_time')") or die_nice(mysqli_error().'tax collection paper');
}
}
	if ($freeplay >= 1){
	$drop_gold *= 2;
	}
	$to_update .= ", `gold`=`gold`+$drop_gold";
	$fight_on .= ' .</font><br>';
}
	//DROP GOLD AND TAX COLLECTIONS

}elseif ($mrow->life > 0 and $row->life < 0) {

	$fight_on .= 'You have been slain by <b>'.$array_monsters[$mrow->charname].'</b>';
	$to_update .= ", `life`=0";
	if($row->exp > $prev_level) {
	if($row->exp-$mon_exp < $prev_level){
		$to_update .= ", `exp`='$prev_level'";
	}else{
		$to_update .= ", `exp`=`exp`-$mon_exp";
	}
	$fight_on .= ', you lost <b>'.number_format($mon_exp).'</b> experience';
	}
	if($row->gold >= 1){
	$to_update .= ", `gold`=`gold`-".$row->gold/50;
	$fight_on .= ', you lost <b>'.number_format($row->gold/50).'</b> gold';
	}
	$fight_on .= '!<br>';

}elseif ($mrow->life < 0 and $row->life < 0) {
	$fight_on .= 'You are both dead! Nobody lost!<br>';
}elseif ($mrow->life > 0 and $row->life > 0) {
	$fight_on .= 'Keep on trying!<br>';
}else{
	$fight_on .= 'Don\'t know what happend here?<br>';
}

$fight_on .= 'You have '.number_format($row->life).' life, '.number_format($row->mana).' mana and '.number_format($row->stamina).' stamina left.<br>';

}
	//WIN OR lOSS

mysqli_query ($link, "UPDATE `$tbl_fight` SET $to_update_monster WHERE `id`='$mrow->id' LIMIT 1") or die_nice(mysqli_error().'monsters timer');
}else{
//ENGAGE BATTLEFIELD



//MONSTER MEMORY
if($row->charname !== $mrow->ocharname){
if (rand(1,100) >= 75) {
mysqli_query ($link, "UPDATE `$tbl_fight` SET `ocharname`='$row->charname' WHERE `id`='$mrow->id'") or die_nice(mysqli_error());
$fight_on .= $array_monsters[$mrow->charname].' is memorizing you.<br>';
} else {
$fight_on .= $array_monsters[$mrow->charname].' did\'t see you at all he was looking at the other way.<br>';
}
}else{
	if(empty($action)){
$array_say = array('say\'s something that you can\'t understand.','is coming for you tonight!', 'GRRR! GRRRRR! GRRRRRR!', 'is watching you very closely!','come and get me if you dare!', 'do you think you can handle me?', 'come on what are you waiting for?','let\'s me see how strong you are!','!@#$%^&*');
$fight_on .= $array_monsters[$mrow->charname].' '.$array_say[array_rand($array_say)].'<br>';
	}
}
//MONSTER MEMORY

}
//FIGHT ON
}
mysqli_free_result ($maresult);
}else{$fight_on .= 'You are dead drink a life potion or visit the healer.<br>';}
}else{$fight_on .= 'Must be already dead or has managed to escape from you.<br>';}
}else{$fight_on .= 'Has escaped.<br>';}

//CREATE ATTACK FORM
?><form method=post action="?">
<table width=100% cellpadding=0 cellspacing=1 border=0><tr><th>Attack</th><th colspan=3><?php
	//MONSTERS LIST
if($mlresult = mysqli_query ($link, "SELECT `id`,`life`,`charname`,`dupe` FROM `$tbl_fight` WHERE (`x`='$row->x' and `y`='$row->y') ORDER BY `charname` ASC LIMIT $max_monsters")) {
if(mysqli_num_rows($mlresult) >= 1){
	?><select name=attack><?php
												//$to_attack_all = '';
while ($mlrow = mysqli_fetch_object ($mlresult)) {
if($mlrow->id == $attack) {$selected =' selected';}else{$selected ='';}
print '<option value="'.$mlrow->id.'"'.$selected.'>Level '.$mlrow->charname.' '.$array_monsters[$mlrow->charname].' '.($mlrow->quests >= 18?ucfirst($array_strength[$mlrow->dupe]):'').' '.($mlrow->life <= 0?'DEAD':'').'</option>';
												//if(!empty($to_attack_all)){$to_attack_all .= ", ";}
												//$to_attack_all .= "$mlrow->id";
}
mysqli_free_result ($mlresult);
	?></select><?php
}
}
	//MONSTERS LIST
?></th></tr><tr><td><input type=submit name=action value="use weapon"></td><td><input type=submit name=action value="heal spell"></td><td><input type=submit name=action value="cast spell"></td></tr>

<tr><td><input type=submit name=action value="use battle skill"></td><td><input type=submit name=action value="run or hide"></td><td><input type=submit name=action value="cast magic skill"></td></tr>

<tr><td><input type=submit name=potion value="life"></td><td><input type=submit name=potion value="mana"></td><td><input type=submit name=potion value="stamina"></td></tr>
</table>
</form><?php
//CREATE ATTACK FORM

?>
</td></tr></table>
<?php
if(!empty($fight_on)){
?><table width=100% cellpadding=0 cellspacing=1 border=0><tr><th>Fight Analysis</th><tr><td><font size=-1><?php
print $fight_on;//$fight_on='';
?></font></td></tr></table><?php
}


if(!empty($attack)){
//NEWS PAPER LOCATION nid 8 shop
news_paper($attack,'6','Scars');
//NEWS PAPER LOCATION nid 8 shop
}
//NOOB
if($row->level <= $noob_level){
$fight_on .= 'Why do I do less damage than my minimum damage? Because the monster also has defense the rest is blocked!<br>';
}
//NOOB
?><table width=100% cellpadding=0 cellspacing=1 border=0>
<tr><th>Battle Engine</th></tr>
<tr><td><font size=-1>You have <b title="If you don't have enough attack or magic rating you still can hit your enemies with succes rate. This chance can be increased by killing allot monsters you will gain more experience in doing things. Walking away in the middle of combat will decrease this value."><?php print round($min_succes_chance+$row->honor,2);?>%</b> succes rate.<br>
Use Weapon, Drink Potion and Run or Hide cost <?php print number_format($use_battle);?> stamina, Cast Spell or Cast Healspell cost <?php print number_format($use_battle);?> mana, Use Battle Skill cost <?php print number_format($use_skill);?> stamina and Casting Magic Spell cost <?php print number_format($use_skill);?> Mana.</font>
</td></tr></table>